import {customOnlyDesign,CUSTOM_DRAFT_KEY,FULL_DRAFT_KEY} from './access-state.mjs';
import {initProfileVisibility,profileNamesUnlocked,maskProfileText,presentProfileHTML} from './profile-visibility.mjs';
import {materialReference,referenceWorkingHTML} from './material-reference.mjs';
import {calculationsHTML,stationHTML} from './calculations.mjs';
import {defaultSteelInsert,flipProfile,supportsSteel,teeForInsert} from './steel.mjs';
import {defaults,normalize,prepareLoadedDesign,validate,evaluate,verify,initialParams} from './solver.mjs';
import {History,calibrationValues,signature,materialBasis} from './design.mjs';
import {defaultRibs,profilePresets,profileSources,applyProfilePreset,ribKeys,isSectionEdit,validateSteelPlacement,validateSection,sectionGeometry,sectionRecord,sectionSVG} from './section.mjs';
import {PathView} from './view.mjs';
import * as exporter from './export.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let accessUnlocked=profileNamesUnlocked(),notice='';
const draftNotices={};
function readDraft(key){try{const saved=localStorage.getItem(key);if(!saved)return null;const loaded=prepareLoadedDesign(JSON.parse(saved));draftNotices[key]=loaded.notice;return loaded.settings;}catch{draftNotices[key]='The saved draft could not be restored. Load a saved file to recover it.';return null;}}
const fullDraft=readDraft(FULL_DRAFT_KEY),customDraft=readDraft(CUSTOM_DRAFT_KEY),modeSessions={};
let state=accessUnlocked?structuredClone(fullDraft||defaults):customOnlyDesign(customDraft||defaults);
notice=draftNotices[accessUnlocked?FULL_DRAFT_KEY:CUSTOM_DRAFT_KEY]||'';
const view=new PathView($('#scene'));let history=new History(state);let tab='profile',worker=null,serial=0,timer=null,current=null,busy=false,bindings=[],comparisons=[];
const number=(n,d=0)=>Number.isFinite(n)?n.toFixed(d):'—';
function announce(message){notice=message;$('#notice').textContent=maskProfileText(message);$('#notice').hidden=!message;}
function commit(){if(!validate(state)){history.push(state);try{localStorage.setItem(accessUnlocked?FULL_DRAFT_KEY:CUSTOM_DRAFT_KEY,JSON.stringify(state));}catch{announce('Browser storage is unavailable. Use Save file to keep your design.');}}$('#undo').disabled=history.index===0;$('#redo').disabled=history.index===history.items.length-1;}
function control([key,label,unit,min,max,step],obj=state){const id='f'+bindings.length;bindings.push({id,key,obj});const v=obj[key];return `<div class="control"><div class="control-head"><label for="${id}-range">${label}</label><div class="number-wrap"><input id="${id}-number" aria-label="${label}, exact value" type="number" min="${min}" max="${max}" step="${step}" value="${Number.isFinite(v)?v:''}"><span>${unit}</span></div></div><input id="${id}-range" aria-label="${label}" type="range" min="${min}" max="${max}" step="${step}" value="${Number.isFinite(v)?v:min}"></div>`;}
function select(key,label,options,obj=state){const id='f'+bindings.length;bindings.push({id,key,obj,type:'select'});return `<label class="field-label" for="${id}">${label}</label><select id="${id}" class="wide-input">${options.map(([v,l])=>`<option value="${v}" ${obj[key]===v?'selected':''}>${l}</option>`).join('')}</select>`;}
function optionalInput(key,label,unit='MPa'){const id='f'+bindings.length;bindings.push({id,key,obj:state.material,type:'optional'});const v=state.material[key];return '<label class="measurement-field" for="'+id+'">'+label+'<span class="measurement-input"><input id="'+id+'" type="number" step="any" '+(key==='temperature'?'':'min="0.000001"')+' placeholder="Not entered" value="'+(Number.isFinite(v)?v:'')+'"><span>'+unit+'</span></span></label>';}
function referenceFields(){const r=materialReference(state);return '<h3>Reference starting stiffness</h3><div class="reference-card"><div id="reference-evidence">'+referenceWorkingHTML(state)+'</div>'+(r.eligible?select('mode','Reference mode',[['auto','Use public reference · 2,758 MPa'],['adjusted','Use an adjusted reference'],['off','Disable reference']],state.material.reference)+'<label class="measurement-field" for="reference-modulus">Reference Young’s modulus<span class="measurement-input"><input id="reference-modulus" type="number" min="0.000001" max="10000000" step="any" value="'+(Number.isFinite(r.valueMPa)?r.valueMPa:'')+'" '+(r.mode==='off'?'disabled':'')+'><span>MPa</span></span></label><p class="small-note">Adjust this starting value or enter a recorded result below. Automatic bending uses recorded flexural modulus, then recorded Young’s modulus, then this reference.</p>':'')+'</div>';}
function refreshReference(){const host=$('#reference-evidence');if(host){const open=host.querySelector('details')?.open;host.innerHTML=presentProfileHTML(referenceWorkingHTML(state));if(open&&host.querySelector('details'))host.querySelector('details').open=true;}if($('#reference-profile-status')){const m=materialBasis(state);$('#reference-profile-status').textContent=m.E===null?'No material modulus active. Add measurements in Material.':m.bendingSource+': '+number(m.E,0)+' MPa'+(state.calibration?' · whole-profile calibration controls the route.':'.');}}
function materialUse(){const m=materialBasis(state),parts=[];if(state.calibration)parts.push('Route stiffness: measured whole-profile calibration.');else if(m.E!==null)parts.push('Route bending: '+m.bendingSource+' ('+number(m.E,1)+' MPa) with the selected section.');else parts.push('Route stiffness: geometric section ratios. Enter a modulus or use sample calibration for a physical stiffness estimate.');if(m.E!==null){parts.push('Nominal bending stress: '+m.bendingSource+' × geometric strain.');if(!state.calibration&&!state.steel.enabled)parts.push('Shear: '+number(m.G,1)+' MPa estimated from '+m.shearSource+' and Poisson’s ratio '+state.material.poisson+'.');}else if(state.material.tensileStrengthMPa!==null||state.material.flexuralStrengthMPa!==null)parts.push('Strength results are stored; enter a modulus to enable the nominal stress comparison.');if(state.steel.enabled)parts.push((m.E===null&&!state.calibration?'PVC modulus missing: the route uses PVC-only geometric bending; steel stiffness is not assessed. ':'')+(state.steel.fit==='bonded'?'No-slip composite bending assumes perfect load transfer. ':'Sliding fit assumes free axial slip and shared curvature; friction is not modelled. ')+(state.calibration?'Calibration represents the complete assembly; steel stiffness is not added twice.':'Reinforced torsion is unestimated; the route minimises bending and applies the geometric twist limit.'));else if(state.section==='ribbed')parts.push('Section geometry is approximate. Ribbed torsion uses an open-wall estimate; sample calibration overrides it but does not measure bending coupling.');if(m.modulusDifferencePercent!==null)parts.push('Flexural modulus is '+number(Math.abs(m.modulusDifferencePercent),1)+'% '+(m.modulusDifferencePercent>=0?'higher':'lower')+' than Young’s modulus. Both records are kept separately.');return parts.join(' ');}
const poseDefs=[['x','Position X','mm',-1000,1000,1],['y','Position Y','mm',-1000,1000,1],['z','Position Z','mm',-1000,1000,1],['yaw','Direction · yaw','°',-180,180,1],['pitch','Direction · pitch','°',-90,90,1],['roll','Section · roll','°',-180,180,1]];

function profileFields(){
 const ribbed=state.section==='ribbed';
 return '<h2>Profile section</h2><p class="field-intro">One constant section. The preview marks the datum used by the pathway and endpoint positions.</p>'+
 (accessUnlocked?select('section','Section model',[['solid','Solid rectangle'],['hollow','Hollow rectangle'],['ribbed','Ribbed PVC · adjustable']]):'<h3>Custom ribbed section</h3>')+
 (ribbed&&accessUnlocked?select('profilePreset','Public profile reference',[['custom','Custom ribbed section'],...profilePresets.map(p=>[p.id,profileSources[p.source].family+' · '+p.id+' · '+p.height+' mm'])])+'<div id="section-source" class="section-source"></div>':'')+
 control(['width','Overall width','mm',1,150,.1])+control(['height','Overall height','mm',1,50,.1])+
 (state.section==='hollow'?control(['wall','Wall thickness','mm',.1,24,.1]):'')+
 '<button id="flip-profile" class="button wide-input" aria-pressed="'+!!state.profileFlipped+'">'+(state.profileFlipped?'↶ Restore original orientation':'↻ Flip profile 180°')+'</button><p class="small-note">Turns PVC and steel together around the travel direction. Endpoint roll settings stay as entered.</p><div id="section-preview" class="section-preview"></div><p id="section-basis" class="small-note"></p>'+
 (ribbed?'<details class="section-editor"><summary>Base and T-ribs</summary><p class="small-note">Dimensions below are adjustable assumptions. Spacing is measured between rib centres.</p>'+[
 ['base','Base thickness','mm',.01,15,.01],['count','Number of ribs','',1,10,1],['pitch','Rib spacing','mm',.1,145,.1],['web','Rib thickness','mm',.01,15,.01],['capWidth','Rib cap width','mm',.01,40,.01],['capThickness','Cap thickness','mm',.01,15,.01]
 ].map(d=>control(d,state.ribbed)).join('')+'</details>':'')+
 steelFields()+'<details class="section-properties"><summary>Section properties and confidence</summary><div id="section-properties"></div></details>'+
 '<h3>Route preference</h3><button id="material-open" class="button">Material measurements · MPa</button><p id="reference-profile-status" class="small-note"></p><p class="small-note">Balance bending demand against route length. Twisting stiffness is included when available. <strong id="stiffness-multiplier"></strong> design weighting.</p>'+control(['stiffness','Bend / twist preference','',0,100,1])+
 '<div class="range-labels"><span>Favour shorter</span><span>Favour gentler</span></div><h3>Measured sample</h3><p class="small-note">'+(state.calibration?'Three measured rigidities are active for this complete assembly. Section or steel geometry changes remove calibration; a 180° flip preserves it.':'Optional: use bending and twisting measurements from the complete assembly, with its steel already fitted if enabled.')+'</p><button id="calibrate" class="button">'+(state.calibration?'Review calibration':'Calibrate from a sample')+'</button>'+(state.calibration?'<button id="remove-calibration" class="text-button">Remove calibration</button>':'');
}

function steelFields(){
 if(!accessUnlocked)return '';
 const a=state.steel;if(!supportsSteel(state))return '<h3>Steel reinforcement</h3><p class="small-note">Encapsulated steel is available only for <strong>91-22ROS and 91-32ROS</strong>, inside their T-ribs. Select either reference under Ribbed PVC to configure it.</p>';
 return '<h3>Steel reinforcement</h3><label class="check left"><input id="steel-enabled" type="checkbox" '+(a.enabled?'checked':'')+'> Encapsulated steel in T-ribs</label><p class="small-note">For 91-22ROS and 91-32ROS only. Steel runs within the T-ribs. Each insert is a rectangular approximation; its dimensions remain editable assumptions.</p>'+(a.enabled?
 select('fit','PVC / steel fit assumption',[['sliding','Sliding fit · axial slip'],['bonded','No slip · bonded fit']],a)+
 '<p class="small-note">Encapsulation does not establish bonding. Sliding fit lets each strip bend about its own centre; no slip uses an elastic centre shared by both materials and requires a PVC modulus in Material.</p>'+
 control(['youngMPa','Steel elastic modulus','MPa',1000,300000,1000],a)+'<p class="small-note">200,000 MPa is an editable steel assumption. Enter your measured value when available. Reinforced torsion is unestimated unless the whole assembly is calibrated.</p>'+
 '<details class="steel-editor"><summary>Insert dimensions and positions ('+a.inserts.length+')</summary><p class="small-note">Centres are measured from the PVC lower-left corner in its original orientation. A flip keeps these entries unchanged. Each insert must stay inside one T-rib with PVC cover. The base is excluded.</p>'+a.inserts.map((v,i)=>'<div class="steel-insert"><h4 data-steel-label="'+i+'">Steel insert '+(i+1)+' · '+(teeForInsert(state,v)>=0?'T-rib '+(teeForInsert(state,v)+1):'check T-rib placement')+'</h4><button class="text-button remove-steel" data-index="'+i+'">Remove insert '+(i+1)+'</button>'+[
 ['width','Insert '+(i+1)+' horizontal width','mm',.01,150,.01],['height','Insert '+(i+1)+' vertical height','mm',.001,50,.001],['x','Insert '+(i+1)+' centre X','mm',0,150,.01],['y','Insert '+(i+1)+' centre Y','mm',0,50,.01]
 ].map(d=>control(d,v)).join('')+'</div>').join('')+'<button id="add-steel" class="button" '+(a.inserts.length>=6||!defaultSteelInsert(state)?'disabled':'')+'>+ Add steel in next T-rib</button><p class="small-note">New inserts start vertically inside the T-web. Up to six inserts; edit the dimensions to match the steel in your profile.</p></details>':'');
}
function fields(){const expanded=[...document.querySelectorAll('#fields details[open]')].map(e=>e.className);bindings=[];let html='';
 if(tab==='profile')html=profileFields();
 else if(tab==='material')html=`<h2>Material stiffness & measurements</h2><p class="field-intro">Use a documented reference to start, or enter your results. 1 MPa = 1 N/mm².</p>${referenceFields()}<h3>Recorded modulus · stiffness</h3>${optionalInput('youngMPa','Young’s / elastic modulus')}${optionalInput('flexuralMPa','Flexural modulus')}${select('bendingBasis','Modulus used for bending',[['auto','Automatic: recorded values, then reference'],['flexural','Use flexural modulus'],['young','Use Young’s · recorded or reference']],state.material)}<h3>Strength · reference values</h3>${optionalInput('tensileStrengthMPa','Tensile strength')}${optionalInput('flexuralStrengthMPa','Flexural strength')}<p class="small-note">Strength values are compared separately with nominal bending stress. They are recorded test results, not allowable design stresses. They do not change the route or its geometric limits.</p><p id="material-use" class="material-use">${esc(materialUse())}</p><details><summary>Shear assumption & measurement details</summary><p class="small-note">For PVC-only routes without whole-profile calibration, shear modulus is estimated as G = E / [2(1 + ν)], assuming isotropic behaviour. ν = 0.38 is an editable starting assumption, not a measured PVC value. If only flexural modulus is available, using it for G is provisional.</p>${control(['poisson','Poisson’s ratio ν','',-.99,.49,.01],state.material)}<label class="measurement-field">Sample / batch / report<input id="material-sample" class="wide-input" value="${esc(state.material.sample)}" maxlength="1000"></label>${optionalInput('temperature','Measurement temperature','°C')}<label class="measurement-field" for="material-notes">Test methods, directions, loading times & notes<textarea id="material-notes" rows="4" maxlength="1000" class="wide-input">${esc(state.material.notes)}</textarea></label></details>${state.calibration?'<p class="small-note">Whole-profile calibration takes precedence for route stiffness. To use modulus-based route stiffness, remove the calibration in Profile. Entered modulus still supports a separate nominal stress estimate.</p>':''}`;
 else if(tab==='limits')html=`<h2>Design limits</h2><p class="field-intro">User-selected geometric targets. Endpoint separation stays within 1,000 mm.</p>${control(['minRadius','Minimum bend radius','mm',1,5000,1])}${control(['maxTwist','Maximum twist','° / 100 mm',.1,180,.1])}${control(['maxLength','Maximum path length','mm',10,5000,10])}${control(['maxStrain','Peak bending strain target','%',0,20,.1])}<p class="small-note">A strain target of 0 disables that target. The displayed strain follows bend geometry; it is not a measured PVC failure limit.</p>`;
 else if(tab==='start'||tab==='end')html=`<h2>${tab==='start'?'Start':'End'} section</h2><p class="field-intro">Position the pathway datum marked in Profile and set the travel direction. Roll turns the ribs around the pathway.</p>${poseDefs.map(d=>control(d,state[tab])).join('')}${control([tab+'Lead','Straight '+(tab==='start'?'inlet':'outlet'),'mm',0,1000,5])}${tab==='end'?select('endRollMode','Outlet roll',[['fixed','Hold the selected roll'],['range','Allow a roll range'],['free','Let the route choose roll']])+(state.endRollMode==='range'?control(['rollRange','Allowed roll either side','°',0,180,1]):''):''}<p class="small-note">Straight sections match the endpoint direction and keep a constant section orientation.</p>`;
 else if(tab==='clearance')html=`<h2>Clearance</h2><p class="field-intro">Check the outer envelope about the selected pathway datum, including a gap around every side. Spaces between ribs are not available clearance.</p>${control(['clearance','Gap on each side','mm',0,50,.5])}<h3>Obstacles</h3><div class="button-row"><button id="add-box" class="button">+ Box</button><button id="add-cylinder" class="button">+ Cylinder</button></div>${state.obstacles.map((o,i)=>`<details class="obstacle" ${i===state.obstacles.length-1?'open':''}><summary>${esc(o.name||('Obstacle '+(i+1)))}</summary><button class="text-button remove-obstacle" data-index="${i}">Remove</button>${[['x','Centre X'],['y','Centre Y'],['z','Centre Z']].map(([k,l])=>control([k,l,'mm',-2000,2000,1],o)).join('')}${(o.type==='box'?[['w','Size X'],['d','Size Y'],['h','Size Z']]:[['radius','Radius'],['h','Height']]).map(([k,l])=>control([k,l,'mm',1,2000,1],o)).join('')}</details>`).join('')}<h3>Available workspace</h3><label class="check left"><input id="workspace-enabled" type="checkbox" ${state.workspace.enabled?'checked':''}> Limit the whole sweep to a box</label>${state.workspace.enabled?[['x','Centre X',-2000],['y','Centre Y',-2000],['z','Centre Z',-2000],['w','Size X',1],['d','Size Y',1],['h','Size Z',1]].map(([k,l,min])=>control([k,l,'mm',min,5000,1],state.workspace)).join(''):''}<p class="small-note">Obstacle and workspace checks include the gap. Self-contact uses the outer envelope. An unresolved close approach blocks CAD export.</p>`;
 else html=`<h2>Saved designs</h2><p class="field-intro">Your latest valid design is kept in this browser. ${accessUnlocked?'Save a file to move it between computers.':''}</p><div class="button-row"><button id="save-file-panel" class="button" ${accessUnlocked?'':'hidden'}>Save file</button><button id="load-file-panel" class="button">Load file</button></div><h3>Compare designs</h3><p class="small-note">Keep up to three routes, change the settings, then compare results. Comparisons stay in this session.</p><button id="keep-design" class="button" ${!current?.refined||busy?'disabled':''}>Keep current route</button><div id="comparison-list">${comparisonHTML()}</div><h3>Starting points</h3><button id="reset-default" class="button">Original example</button><button id="straight-example" class="button">Straight example</button>`;
 $('#fields').innerHTML=presentProfileHTML(html);for(const e of document.querySelectorAll('#fields details'))if(expanded.includes(e.className))e.open=true;
 for(const b of bindings){if(b.type==='optional'){const input=$('#'+b.id);input.oninput=()=>{b.obj[b.key]=input.validity.badInput?NaN:input.value.trim()===''?null:input.valueAsNumber;changed();refreshReference();if($('#material-use'))$('#material-use').textContent=maskProfileText(validate(state)||materialUse());};input.onchange=commit;continue;}if(b.type==='select'){$('#'+b.id).onchange=e=>{if(b.key==='profilePreset'&&e.target.value!=='custom'){const calibrated=!!state.calibration,hadSteel=state.steel.enabled;state=applyProfilePreset(state,e.target.value);announce('Reference height applied. Width is retained; ribs are illustrative assumptions.'+(calibrated?' Previous sample calibration has been removed.':'')+(hadSteel?' Steel was turned off for the profile change. Only 91-22ROS and 91-32ROS support encapsulated T-rib steel.':''));view.fit();}else{b.obj[b.key]=e.target.value;if(b.obj===state.material.reference&&b.key==='mode'&&e.target.value==='auto')b.obj.valueMPa=2758;sectionChanged(b.key,b.obj);}fields();changed();commit();};continue;}for(const type of ['number','range']){const input=$('#'+b.id+'-'+type);input.oninput=()=>{b.obj[b.key]=input.valueAsNumber;const other=$('#'+b.id+'-'+(type==='number'?'range':'number'));if(Number.isFinite(b.obj[b.key]))other.value=b.obj[b.key];sectionChanged(b.key,b.obj);profileSketch();changed();};input.onchange=commit;}}
 if($('#reference-modulus')){const input=$('#reference-modulus');input.oninput=()=>{state.material.reference.valueMPa=input.validity.badInput?NaN:input.valueAsNumber;state.material.reference.mode='adjusted';const choice=bindings.find(b=>b.obj===state.material.reference&&b.key==='mode');if(choice)$('#'+choice.id).value='adjusted';changed();refreshReference();};input.onchange=commit;}
 if($('#flip-profile'))$('#flip-profile').onclick=()=>{state=flipProfile(state);fields();changed();commit();};
 if($('#steel-enabled'))$('#steel-enabled').onchange=e=>{state.steel.enabled=e.target.checked;announce(state.steel.enabled?'Steel enabled in the T-ribs. Review the insert dimensions against your profile.':'Steel reinforcement turned off.');if(state.steel.enabled&&(!state.steel.inserts.length||validateSteelPlacement(state))){if(state.steel.inserts.length)state.steel.previousInserts=structuredClone(state.steel.inserts);state.steel.inserts=[];let item;while(state.steel.inserts.length<6&&(item=defaultSteelInsert(state)))state.steel.inserts.push(item);announce('Example steel inserts placed vertically inside the T-ribs. Adjust their dimensions to match your profile.');}sectionChanged('enabled',state.steel);fields();changed();commit();};
 if($('#add-steel'))$('#add-steel').onclick=()=>{if(state.steel.inserts.length>=6)return;const item=defaultSteelInsert(state);if(!item)return;state.steel.inserts.push(item);sectionChanged('inserts',state.steel);fields();changed();commit();};
 document.querySelectorAll('.remove-steel').forEach(b=>b.onclick=()=>{state.steel.inserts.splice(Number(b.dataset.index),1);if(!state.steel.inserts.length)state.steel.enabled=false;sectionChanged('inserts',state.steel);fields();changed();commit();});
 if($('#material-open'))$('#material-open').onclick=()=>document.querySelector('[data-tab=material]').click();for(const k of ['sample','notes'])if($('#material-'+k))$('#material-'+k).onchange=e=>{state.material[k]=e.target.value;commit();};
 if($('#calibrate'))$('#calibrate').onclick=openCalibration;if($('#remove-calibration'))$('#remove-calibration').onclick=()=>{state.calibration=null;fields();changed();commit();};
 for(const type of ['box','cylinder'])if($('#add-'+type))$('#add-'+type).onclick=()=>{if(state.obstacles.length>=12){announce('The design supports up to 12 obstacles.');return;}state.obstacles.push({type,name:(type==='box'?'Box ':'Cylinder ')+(state.obstacles.length+1),x:350,y:250,z:0,w:100,d:100,h:150,radius:50});fields();changed();commit();};
 document.querySelectorAll('.remove-obstacle').forEach(b=>b.onclick=()=>{state.obstacles.splice(Number(b.dataset.index),1);fields();changed();commit();});if($('#workspace-enabled'))$('#workspace-enabled').onchange=e=>{state.workspace.enabled=e.target.checked;fields();changed();commit();};
 if(tab==='saved'){$('#save-file-panel').onclick=saveFile;$('#load-file-panel').onclick=()=>$('#load-file').click();$('#keep-design').onclick=()=>{if(current?.refined){if(comparisons.length===3)comparisons.shift();comparisons.push({settings:structuredClone(state),result:structuredClone(current)});fields();}};document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>restore(comparisons[Number(b.dataset.restore)].settings));$('#reset-default').onclick=()=>restore(accessUnlocked?defaults:customOnlyDesign(defaults));$('#straight-example').onclick=()=>restore({...structuredClone(accessUnlocked?defaults:customOnlyDesign(defaults)),end:{x:800,y:0,z:0,yaw:0,pitch:0,roll:0}});}
 profileSketch();refreshReference();
}
function sectionChanged(key,obj){if(obj===state&&['section','profilePreset'].includes(key)&&!supportsSteel(state)&&state.steel.enabled){if(state.calibration)state.steel.inactiveCalibration=state.calibration;state.steel.enabled=false;state.calibration=null;announce('Steel is inactive: encapsulation is limited to T-ribs in 91-22ROS and 91-32ROS.');}if(obj===state&&key==='section'){state.profilePreset='custom';state.steel.enabled=false;if(state.section==='ribbed')state.ribbed=defaultRibs(state.width,state.height);}if(isSectionEdit(state,obj,key)&&state.calibration){state.calibration=null;const button=$('#calibrate');if(button){button.textContent='Calibrate from a sample';button.previousElementSibling.textContent='Optional: use bending and twisting measurements from the complete assembly, with steel fitted if enabled.';}$('#remove-calibration')?.remove();announce('Section changed. The previous sample calibration has been removed.');}}
function profileSketch(){
 if(tab!=='profile')return;
 document.querySelectorAll('[data-steel-label]').forEach(e=>{const i=Number(e.dataset.steelLabel),tee=teeForInsert(state,state.steel.inserts[i]);e.textContent='Steel insert '+(i+1)+' · '+(tee>=0?'T-rib '+(tee+1):'check T-rib placement');});
 if($('#add-steel'))$('#add-steel').disabled=state.steel.inserts.length>=6||!defaultSteelInsert(state);
 $('#stiffness-multiplier').textContent=(10**((state.stiffness-50)/50)).toFixed(2)+'×';
 const error=validateSection(state)||(state.section==='hollow'&&(!Number.isFinite(state.wall)||state.wall<=0||2*state.wall>=Math.min(state.width,state.height))?'Check the wall thickness.':null)||(!Number.isFinite(state.width)||!Number.isFinite(state.height)||state.width<1||state.width>150||state.height<1||state.height>50?'Check the overall section dimensions.':null)||validateSteelPlacement(state);
 if(error){$('#section-preview').textContent=maskProfileText(error);$('#section-basis').textContent='Preview updates when the section dimensions fit together.';$('#section-properties').textContent='Check the section inputs.';if($('#section-source'))$('#section-source').textContent='The current dimensions need adjustment.';return;}
 const g=sectionGeometry(state),record=sectionRecord(state),ref=record.reference;
 $('#section-preview').innerHTML=sectionSVG(state);
 $('#section-basis').textContent=state.section==='ribbed'?(ref?(ref.heightMatchesPublished?'Height matches the published '+ref.publishedHeight_mm+' mm. ':'Height edited from the published '+ref.publishedHeight_mm+' mm. '):'Custom height. ')+'Width and ribs are unsourced dimensions. Clearance uses the full outer envelope, including the empty rib channels.':'The cross marks '+g.datumKind.toLowerCase()+' used by endpoint positions and the pathway.';
 if($('#section-source'))$('#section-source').innerHTML=presentProfileHTML(ref?'<strong>'+esc(ref.profile)+' · approximate section</strong><p>Public reference for height only. Other dimensions remain adjustable assumptions.</p><a href="'+esc(ref.source.url)+'" target="_blank" rel="noreferrer">'+esc(ref.source.family)+' brochure · page '+ref.source.page+'</a>':'<strong>Custom ribbed section</strong><p>All dimensions are user-selected. Choose a public reference to use a published height.</p>');
 $('#section-properties').innerHTML='<dl class="property-list">'+[['Total material area',number(g.area,2)+' mm²'],...(state.steel.enabled?[['PVC area',number(g.pvcArea,2)+' mm²'],['Steel area',number(g.steelArea,2)+' mm²']]:[]),['Pathway datum',g.datumKind],['Width-direction moment',number(g.Iyy,1)+' mm⁴'],['Height-direction moment',number(g.Ixx,1)+' mm⁴'],['Coupled moment',number(g.Ixy,1)+' mm⁴'],['Torsion constant ≈',number(g.J,2)+' mm⁴']].map(([a,b])=>'<div><dt>'+a+'</dt><dd>'+b+'</dd></div>').join('')+'</dl><p class="small-note">'+esc(record.geometryConfidence)+'</p><p class="small-note">'+esc(record.stiffnessConfidence)+' '+esc(g.torsionNote)+'</p>'+(state.section==='ribbed'?'<p class="small-note">Product names do not supply steel dimensions or measured stiffness. Nominal stress excludes local rib and lock deformation.</p>':'');
}

function comparisonHTML(){return comparisons.map((c,i)=>`<div class="comparison"><strong>Design ${i+1}</strong><p>${number(c.result.length)} mm long · ${c.result.radius?number(c.result.radius):'∞'} mm minimum radius<br>${number(c.result.twistMax,1)}° twist / 100 mm · ${number(c.result.strainMax*100,2)}% peak strain<br>Clearance: ${esc(c.result.clearance?.status||'unchecked')}</p><button class="text-button" data-restore="${i}">Restore settings</button></div>`).join('');}
function invalidate(message){worker?.terminate();worker=null;clearTimeout(timer);serial++;busy=false;current=null;$('#input-error').hidden=false;$('#input-error').textContent=maskProfileText(message);$('#status').textContent='Check the design inputs';$('#solver-detail').textContent='';$('#export-open').disabled=true;$('#refine').disabled=true;$('#metrics').innerHTML='';$('#analysis').hidden=true;clearCalculations();view.set(null,state);}
function changed(){const error=validate(state);if(error){invalidate(error);return;}$('#input-error').hidden=true;$('#refine').disabled=false;worker?.terminate();worker=null;serial++;busy=false;clearTimeout(timer);current=evaluate(state,initialParams(),180,true);current.refined=false;render();if($('#auto').checked){$('#status').textContent='Updating pathway…';$('#export-open').disabled=true;timer=setTimeout(refine,300);}}
function render(){refreshReference();const r=current;if(!r?.samples){view.set(null,state);$('#metrics').innerHTML='';$('#analysis').hidden=true;$('#solver-detail').textContent='';$('#status').textContent=maskProfileText(r?.error||'No pathway to display');$('#export-open').disabled=true;clearCalculations();return;}view.set(r,state);$('#separation').textContent=`${number(r.separation)} mm separation / 1,000 mm`;$('#analysis').hidden=false;
 $('#metrics').innerHTML=[['Path length',number(r.length),'mm'],['Smallest bend radius ≈',r.radius?number(r.radius):'∞','mm'],['Peak twist ≈',number(r.twistMax,1),'° / 100 mm'],['Peak PVC bending strain ≈',number(r.strainMax*100,2),'%']].map(([l,v,u])=>`<div class="metric"><label>${l}</label><strong>${v}</strong><small>${u}</small></div>`).join('');
 $('#status').textContent=busy?'Refining pathway…':r.refined?(r.feasible?'Best route found · within selected checks':'No feasible route found within this search'):'Unrefined pathway';$('#status').style.color=r.refined&&!r.feasible?'var(--status-warning)':'var(--status-text)';$('#solver-detail').textContent=r.refined?(r.feasible?'Geometry stabilised · sweep checked':r.warnings?.join(' · ')||r.clearance?.status||'Check design limits'):'Refine to check this route';$('#export-open').disabled=!accessUnlocked||busy||!r.refined||!r.feasible;
 $('#clearance-result').textContent=r.clearance?`Envelope clearance ${r.clearance.status} · ${r.clearance.stations} sections · ${r.clearance.margin_mm} mm gap`:'Clearance has not been checked';$('#clearance-result').className=r.clearance?.status==='clear'?'check-result':'check-result caution';
 $('#issues').innerHTML=(r.clearance?.issues||[]).map((v,i)=>`<button class="issue" data-issue="${i}">${esc(v.label)} · ${esc(v.kind)} · ${number(v.from)}–${number(v.to)} mm</button>`).join('');document.querySelectorAll('[data-issue]').forEach(b=>b.onclick=()=>{const issue=r.clearance.issues[Number(b.dataset.issue)];$('#station').value=1000*issue.from/r.length;stationChanged();});
 $('#actual-roll').textContent=state.endRollMode!=='fixed'?`Chosen outlet roll: ${number(r.actualEndRoll,1)}°`:'';$('#energy').textContent=r.physicalEnergy!==null?`Elastic energy estimate: ${number(r.physicalEnergy,1)} N·mm (does not include pushing or contact).`:r.bendingEnergy!==null?`Bending energy estimate: ${number(r.bendingEnergy,1)} N·mm. Reinforced torsion is unestimated.`:state.steel.enabled?'Reinforced stiffness unavailable: enter a PVC modulus or calibrate the whole assembly.':'';
 const m=r.material;$('#material-result').hidden=!m||(!state.calibration&&!state.steel.enabled&&m.E===null&&m.comparisons.length===0);
 if(m){const rows=m.comparisons.map(c=>'<tr><td>'+esc(c.label)+'</td><td>'+number(c.recordedMPa,2)+' MPa</td><td>'+(c.ratio===null?'Needs a modulus':number(c.ratio*100,1)+'% of recorded value')+'</td></tr>').join('');$('#material-result').innerHTML='<strong>'+(m.nominalBendingStressMPa===null?'Nominal PVC bending stress: unavailable':'Nominal PVC bending stress ≈ '+number(m.nominalBendingStressMPa,2)+' MPa')+'</strong><p>'+(m.stressBasis?esc(m.stressBasis):'Enter Young’s or flexural modulus for a stress estimate. Sample calibration alone is not converted into a material modulus.')+'</p>'+ (rows?'<table><thead><tr><th>Reference</th><th>Recorded</th><th>Stress comparison</th></tr></thead><tbody>'+rows+'</tbody></table>':'')+(m.comparisons.some(c=>c.ratio>=1)?'<p class="caution">Nominal bending stress reaches or exceeds a recorded strength. Review the pathway and test conditions.</p>':'')+'<p>Screening only: recorded strengths are not allowable stresses. Compression, twisting stress, pushing and buckling are excluded. No safety factor is applied.</p>';}
 if(m?.reference.usedForBending)$('#material-result').innerHTML+='<p class="reference-result">'+esc(m.reference.label)+': '+number(m.E,0)+' MPa. This stress estimate uses a reference input, not a specimen measurement.</p>';
 if(r.steel)$('#material-result').innerHTML+='<div class="steel-result"><strong>Steel bending strain ≈ '+number(r.steel.peakStrain*100,3)+'% · stress ≈ '+number(r.steel.nominalBendingStressMPa,2)+' MPa</strong><p>'+esc(state.steel.fit==='bonded'?'No-slip fit: perfect load transfer assumed.':'Sliding fit: separate strips share curvature with free axial slip.')+' '+esc(r.rigidity.source)+'.</p><p>'+esc(r.steel.note)+'</p></div>';
 if($('#material-use'))$('#material-use').textContent=materialUse();renderCalculations();chart();stationChanged();if(tab==='saved')fields();
}
function refine(){const err=validate(state);if(err){invalidate(err);return;}clearTimeout(timer);worker?.terminate();busy=true;const id=++serial;$('#status').textContent='Refining pathway…';$('#solver-detail').textContent='Exploring candidate routes';if($('#math-path-status'))$('#math-path-status').textContent='Refining… working shows the current preview';$('#export-open').disabled=true;worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});worker.onmessage=e=>{if(e.data.id!==serial)return;if(e.data.progress){$('#solver-detail').textContent=`Candidate ${e.data.progress.seed} of ${e.data.progress.total}`;return;}busy=false;current=e.data.result;worker.terminate();worker=null;render();};worker.onerror=e=>{busy=false;worker?.terminate();worker=null;$('#status').textContent='Route refinement could not finish';if($('#math-path-status'))$('#math-path-status').textContent='Refinement failed · working shows the current preview';$('#solver-detail').textContent=e.message||'Try refining again';$('#export-open').disabled=true;};worker.postMessage({id,state:structuredClone(state)});}
function chart(){if(!current?.samples)return;const mode=$('#colour-mode').value,values=current.samples.map(q=>mode==='twist'?Math.abs(q.twist):mode==='strain'?q.strain*100:q.k*1000),max=Math.max(...values,1e-9),path=current.samples.map((q,i)=>`${i?'L':'M'}${(q.s/current.length*600).toFixed(2)},${(75-values[i]/max*65).toFixed(2)}`).join(' ');$('#chart').innerHTML=`<path d="${path}" fill="none" stroke="var(--chart-line)" stroke-width="2"/><path d="M0 76H600" stroke="var(--chart-baseline)"/>`;$('#chart-scale').textContent=mode==='twist'?`Peak ${number(max,2)}° / 100 mm`:mode==='strain'?`Peak ${number(max,2)}% bending strain`:`Peak curvature ${number(max,3)} / m`;view.colorMode=mode;view.draw();}
function stationChanged(){if(!current?.samples)return;const target=Number($('#station').value)/1000*current.length,q=current.samples.reduce((a,b)=>Math.abs(b.s-target)<Math.abs(a.s-target)?b:a);view.station=q.s;view.draw();$('#station-info').textContent=`Station ${number(q.s,1)} mm · radius ${q.k>1e-10?number(1/q.k):'∞'} mm · twist ${number(q.twist,2)}° / 100 mm · strain ${number(q.strain*100,2)}%`;const slider=$('#calculation-station');if(slider)slider.value=$('#station').value;const host=$('#math-station');if(host){const opened=host.querySelector('details')?.open;host.innerHTML=stationHTML(current,q);if(opened)host.querySelector('details').open=true;}}
function clearCalculations(){$('#calculations-open').disabled=true;$('#calculations-content').replaceChildren();}
function renderCalculations(){
 const host=$('#calculations-content'),expanded=[...host.querySelectorAll('details[open]')].map(d=>d.dataset.mathSection);
 host.innerHTML=presentProfileHTML(calculationsHTML(current));$('#math-station').innerHTML=stationHTML(current,current.samples[0]);$('#calculations-open').disabled=false;
 for(const id of expanded){const d=host.querySelector('[data-math-section="'+id+'"]');if(d)d.open=true;}
 $('#calculation-station').value=$('#station').value;
 $('#calculation-station').oninput=e=>{$('#station').value=e.target.value;stationChanged();};
 const jump=i=>{$('#station').value=1000*current.samples[i].s/current.length;stationChanged();};
 $('#math-peak-strain').onclick=()=>jump(current.strainIndex);$('#math-tightest-bend').onclick=()=>jump(current.kindex);
}
$('#calculations-open').onclick=()=>{const panel=$('#calculations-panel');panel.open=true;panel.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};
function restore(next){const loaded=prepareLoadedDesign(next);if(!accessUnlocked&&(loaded.settings.section!=='ribbed'||loaded.settings.profilePreset!=='custom'||loaded.settings.steel.enabled))throw Error('Enter the code to load this design.');commit();state=loaded.settings;fields();changed();commit();view.fit();if(loaded.notice)announce(loaded.notice);return loaded.notice;}
function blobDownload(content,name,type){if(!accessUnlocked)return;const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function saveFile(){if(!accessUnlocked)return;const err=validate(state);if(err){announce('Fix the inputs before saving: '+err);return;}commit();blobDownload(JSON.stringify({format:'pvc-pathway-design-v9',settings:state},null,2),'pvc-design.json','application/json');}
$('#load-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>5e6)throw Error('The file exceeds 5 MB.');const data=JSON.parse(await f.text());const note=restore(data.settings||data);announce(note||'Design loaded. The route is being recalculated.');}catch(err){announce('Could not load design: '+err.message);}e.target.value='';};
$('#save-file').onclick=saveFile;$('#load-open').onclick=()=>$('#load-file').click();$('#undo').onclick=()=>{const invalid=validate(state);commit();const s=invalid?structuredClone(history.items[history.index]):history.undo();if(s){state=s;fields();changed();commit();}};$('#redo').onclick=()=>{const s=history.redo();if(s){state=s;fields();changed();commit();}};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();(e.shiftKey?$('#redo'):$('#undo')).click();}});
function openCalibration(){const c=state.calibration||{width:{span:500,force:'',deflection:''},height:{span:500,force:'',deflection:''},torsion:{span:500,torque:'',angle:''},sample:'',temperature:'',timing:''};$('#calibration-fields').innerHTML=['width','height','torsion'].map(k=>`<fieldset><legend>${k==='torsion'?'Twisting test':'Bending toward profile '+k}</legend>${(k==='torsion'?[['span','Gauge length between marks (mm)'],['torque','Added torque (N·m)'],['angle','Additional twist (degrees)']]:[['span','Support-centre span (mm)'],['force','Added centre load (N)'],['deflection','Additional midpoint deflection (mm)']]).map(([key,label])=>`<label>${label}<input type="number" min="0.000001" step="any" data-cal="${k}.${key}" value="${esc(c[k][key])}" required></label>`).join('')}</fieldset>`).join('')+[['sample','Sample ID'],['temperature','Temperature (°C)'],['timing','Time after loading / notes']].map(([k,l])=>`<label class="field-label">${l}<input class="wide-input" data-meta="${k}" value="${esc(c[k]||'')}" maxlength="300"></label>`).join('');$('#calibration-error').textContent='';$('#calibration-dialog').showModal();}
$('#apply-calibration').onclick=()=>{try{const c={width:{},height:{},torsion:{},signature:signature(state)};document.querySelectorAll('[data-cal]').forEach(e=>{const [a,b]=e.dataset.cal.split('.');c[a][b]=e.valueAsNumber;});document.querySelectorAll('[data-meta]').forEach(e=>c[e.dataset.meta]=e.value);const v=calibrationValues(c);state.calibration=c;$('#calibration-dialog').close();fields();changed();commit();const hints=[];for(const k of ['width','height']){const q=c[k];if(q.deflection/q.span>.02||q.span/state[k]<16)hints.push(k+' bend assumptions need review');}announce(`Calibration applied: width ${v.Bw.toExponential(3)}, height ${v.Bh.toExponential(3)}, torsion ${v.C.toExponential(3)} N·mm².${hints.length?' Screening advice: '+hints.join('; ')+'.':''}`);}catch(e){$('#calibration-error').textContent=e.message;}};
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{commit();tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));fields();};for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{view.view(b.dataset.view);document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));};$('#fit').onclick=()=>view.fit();$('#refine').onclick=refine;$('#auto').onchange=()=>{$('#auto').checked?refine():clearTimeout(timer);};$('#colour-mode').onchange=chart;$('#station').oninput=stationChanged;$('#model-open').onclick=()=>$('#model-dialog').showModal();$('#export-open').onclick=()=>{if(accessUnlocked)$('#export-dialog').showModal();};
for(const fmt of ['csv','json','dxf','report'])$('#'+fmt+'-export').onclick=()=>{if(!accessUnlocked)return;const spacing=$('#station-spacing').valueAsNumber;if(!Number.isFinite(spacing)||spacing<1||spacing>100){$('#station-spacing').setCustomValidity('Use a spacing from 1 to 100 mm.');$('#station-spacing').reportValidity();return;}$('#station-spacing').setCustomValidity('');if(!current?.refined||busy||!current.feasible)return;const checked=verify(state,current.params);if(!checked.feasible){current=checked;render();$('#export-dialog').close();announce('The export recheck needs attention.');return;}const output=exporter[fmt](checked,spacing);blobDownload(fmt==='report'?presentProfileHTML(output):output,'pvc-pathway.'+(fmt==='report'?'html':fmt),fmt==='json'?'application/json':fmt==='report'?'text/html':'text/plain');};
if(document.modelContext?.registerTool){const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t)).catch(()=>{});}catch{}};register({name:'read_pathway_design',description:'Read the current design, convergence and clearance results.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>({settings:structuredClone(state),busy,result:current?{length:current.length,radius:current.radius,twist:current.twistMax,strain:current.strainMax,steel:current.steel,clearance:current.clearance,material:current.material,refined:current.refined,withinLimits:current.feasible}:null})});register({name:'set_profile_stiffness',description:'Set relative stiffness and refine.',inputSchema:{type:'object',properties:{stiffness:{type:'number',minimum:0,maximum:100}},required:['stiffness'],additionalProperties:false},execute:input=>{if(!Number.isFinite(input?.stiffness)||input.stiffness<0||input.stiffness>100)throw Error('Stiffness must be 0–100');restore({...state,stiffness:input.stiffness});return{updating:true};}});register({name:'configure_pathway',description:'Load a complete design settings object and refine.',inputSchema:{type:'object',properties:{settings:{type:'object'}},required:['settings'],additionalProperties:false},execute:input=>{restore(input.settings);return{updating:true,settings:structuredClone(state)};}});}
const modelDetailsMarkup=$('#model-dialog').innerHTML;
$('#profile-names-open').addEventListener('click',commit);
initProfileVisibility(()=>{
  const nextAccess=profileNamesUnlocked(),modeChanged=nextAccess!==accessUnlocked;
  const scroll=$('.sidebar-content').scrollTop;
  if(modeChanged){
    commit();modeSessions[accessUnlocked?'full':'custom']={state:structuredClone(state),history,comparisons,notice};
    const savedSession=modeSessions[nextAccess?'full':'custom'];
    state=savedSession?structuredClone(savedSession.state):nextAccess?structuredClone(fullDraft||state):customOnlyDesign(customDraft||defaults);
    history=savedSession?.history||new History(state);comparisons=savedSession?.comparisons||[];
    accessUnlocked=nextAccess;notice=savedSession?.notice||draftNotices[accessUnlocked?FULL_DRAFT_KEY:CUSTOM_DRAFT_KEY]||'';
  }
  $('#save-file').hidden=!accessUnlocked;$('#export-open').hidden=!accessUnlocked;
  if(!accessUnlocked)$('#export-dialog').close();
  fields();$('.sidebar-content').scrollTop=scroll;
  $('#model-dialog').innerHTML=presentProfileHTML(modelDetailsMarkup);
  if(modeChanged){changed();commit();view.fit();}else if(current?.samples){renderCalculations();stationChanged();}
  if(!$('#input-error').hidden)$('#input-error').textContent=maskProfileText(validate(state)||'Check the design inputs.');
  announce(notice);
});
fields();changed();commit();announce(notice);
