import {sectionGeometry,envelopeLoop,sectionPoint} from './section.mjs';
const add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),mul=(a,k)=>a.map(v=>v*k),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>Math.hypot(...a),unit=a=>mul(a,1/(norm(a)||1));
const world=[[1,0,0],[0,1,0],[0,0,1]],EPS=1e-7;
export const corners=(q,w,h,gap=0)=>[[-1,-1],[1,-1],[1,1],[-1,1]].map(([a,b])=>add(q.p,add(mul(q.a,a*(w/2+gap)),mul(q.b,b*(h/2+gap)))));
const bounds=p=>world.map((_,i)=>[Math.min(...p.map(v=>v[i])),Math.max(...p.map(v=>v[i]))]);
const overlap=(a,b)=>a.every((v,i)=>v[1]>=b[i][0]-EPS&&b[i][1]>=v[0]-EPS);
function axesFor(p){const a=unit(sub(p[1],p[0])),b=unit(sub(p[p.length===8?2:3],p[0]));return[a,b,unit(cross(a,b))];}
function box(p,axes){const ranges=axes.map(a=>[Math.min(...p.map(v=>dot(v,a))),Math.max(...p.map(v=>dot(v,a)))]);return{p,axes,ranges,bounds:bounds(p)};}
function boxPoints(o){return Array.from({length:8},(_,i)=>[o.x+(i&1?1:-1)*o.w/2,o.y+(i&2?1:-1)*o.d/2,o.z+(i&4?1:-1)*o.h/2]);}
function sat(a,b){if(!overlap(a.bounds,b.bounds))return false;const candidates=[...a.axes,...b.axes,...a.axes.flatMap(x=>b.axes.map(y=>cross(x,y)))];for(const ax of candidates){if(norm(ax)<EPS)continue;let aa=a.p.map(p=>dot(p,ax)),bb=b.p.map(p=>dot(p,ax));if(Math.max(...aa)<Math.min(...bb)-EPS||Math.max(...bb)<Math.min(...aa)-EPS)return false;}return true;}
function hull(points){const p=points.map(v=>v.slice(0,2)).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);if(p.length<3)return p;const cr=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);let lo=[],hi=[];for(const v of p){while(lo.length>1&&cr(lo.at(-2),lo.at(-1),v)<=EPS)lo.pop();lo.push(v);}for(const v of p.slice().reverse()){while(hi.length>1&&cr(hi.at(-2),hi.at(-1),v)<=EPS)hi.pop();hi.push(v);}return lo.slice(0,-1).concat(hi.slice(0,-1));}
function cylinder(p,o){const low=o.z-o.h/2,high=o.z+o.h/2,clipped=p.filter(v=>v[2]>=low-EPS&&v[2]<=high+EPS);for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++)for(const z of [low,high]){const dz=p[j][2]-p[i][2];if(Math.abs(dz)<EPS)continue;const t=(z-p[i][2])/dz;if(t>=0&&t<=1)clipped.push(add(p[i],mul(sub(p[j],p[i]),t)));}if(!clipped.length)return false;const h=hull(clipped),c=[o.x,o.y];if(!h.length)return false;let inside=h.length>=3,min=Infinity;for(let i=0;i<h.length;i++){const a=h[i],b=h[(i+1)%h.length],d=sub(b,a),v=sub(c,a),t=Math.max(0,Math.min(1,dot(v,d)/(dot(d,d)||1))),dist=norm(sub(c,add(a,mul(d,t))));min=Math.min(min,dist);if(d[0]*v[1]-d[1]*v[0]<-EPS)inside=false;}return inside||min<=o.radius+EPS;}
function intersects(p,o){return o.type==='cylinder'?cylinder(p,o):sat(box(p,axesFor(p)),box(boxPoints(o),world));}
function enclosure(points,axes){const b=box(points,axes),p=[];for(let i=0;i<8;i++){let v=[0,0,0];for(let j=0;j<3;j++)v=add(v,mul(axes[j],b.ranges[j][i>>j&1]));p.push(v);}return p;}
const mix=(a,b)=>a.map((p,i)=>mul(add(p,b[i]),.5));
export function checkClearance(r,s,{self=true,tolerance=.25}={}){
  if(!r.samples)return{status:'unresolved',issues:[],note:'No curve to check'};
  const gap=s.clearance||0,obstacles=s.obstacles||[],issues=[],g=sectionGeometry(s),outer=envelopeLoop(g,gap),materialEnvelope=envelopeLoop(g),rings=r.samples.map(q=>({s:q.s,p:outer.map(p=>sectionPoint(q,p))})),physical=r.samples.map(q=>materialEnvelope.map(p=>sectionPoint(q,p)));
  const record=(kind,label,a,b)=>{if(!issues.some(v=>v.kind===kind&&v.label===label))issues.push({kind,label,from:a,to:b});};
  function interval(a,b,o,depth=0,ax=axesFor(a.p)){const env=enclosure([...a.p,...b.p],ax);if(!intersects(env,o))return;const mid={p:mix(a.p,b.p),s:(a.s+b.s)/2};if([a,mid,b].some(q=>intersects(q.p,o))){record('clash',o.name||'Obstacle',a.s,b.s);return;}if(b.s-a.s<=tolerance||depth>=12){record('unresolved',o.name||'Obstacle',a.s,b.s);return;}interval(a,mid,o,depth+1,ax);interval(mid,b,o,depth+1,ax);}
  for(const o of obstacles)for(let i=1;i<rings.length;i++)interval(rings[i-1],rings[i],o);
  if(s.workspace?.enabled){const ws=s.workspace;for(let i=0;i<rings.length;i++)if(rings[i].p.some(p=>p.some((v,k)=>Math.abs(v-[ws.x,ws.y,ws.z][k])>[ws.w,ws.d,ws.h][k]/2+EPS)))record('clash','Workspace boundary',rings[i].s,rings[i].s);}
  // Non-neighbouring physical cells only. Shared adjacent cells are checked by the local folding limit.
  if(self){const cells=physical.slice(0,-1).map((p,i)=>box([...p,...physical[i+1]],axesFor(p)));for(let i=0;i<cells.length;i++)for(let j=i+2;j<cells.length;j++){if(!sat(cells[i],cells[j]))continue;const a=box(physical[i],axesFor(physical[i])),b=box(physical[j],axesFor(physical[j]));if(sat(a,b))record('clash','Profile envelope self-contact',rings[i].s,rings[j].s);else record('unresolved','Possible profile envelope self-contact',rings[i].s,rings[j+1].s);}}
  const status=issues.some(v=>v.kind==='clash')?'clash':issues.length?'unresolved':'clear';
  return{status,issues,tolerance_mm:tolerance,stations:rings.length,margin_mm:gap,note:'Checks the piecewise linear sweep of the outer rectangular envelope about the section centroid, including the gap. Rib channels are not available clearance: an envelope clash can occur without material contact. Self-contact excludes immediately adjacent cells; local folding is checked separately. Smooth-curve contact between rings remains approximation-dependent.'};
}
export function coarseContact(r,s){if(!r.samples)return 0;let count=0;const outer=envelopeLoop(sectionGeometry(s),s.clearance||0);for(const q of r.samples){const p=outer.map(v=>sectionPoint(q,v));for(const o of s.obstacles||[])if(intersects(p,o))count++;if(s.workspace?.enabled){const w=s.workspace;if(p.some(v=>v.some((x,k)=>Math.abs(x-[w.x,w.y,w.z][k])>[w.w,w.d,w.h][k]/2)))count++;}}return count;}
