import {migrateEdgeLips} from './legacy-section.mjs';
import {steelDefaults,supportsSteel} from './steel.mjs';
import {calibrationValues,signature,sectionProperties,materialDefaults,validateMaterial,rigidity,materialAssessment} from './design.mjs';
import {sectionGeometry,sectionStrains,validateSteelPlacement,validateSection,sectionRecord} from './section.mjs';
import {checkClearance,coarseContact} from './clearance.mjs';
export const defaults = {steel:structuredClone(steelDefaults),profileFlipped:false,material:structuredClone(materialDefaults),section:'solid',wall:1,ribbed:null,profilePreset:'custom',sectionMigration:null,calibration:null,startLead:0,endLead:0,endRollMode:'fixed',rollRange:45,maxStrain:0,clearance:2,obstacles:[],workspace:{enabled:false,x:400,y:0,z:0,w:1400,d:1000,h:1000},width:60,height:8,stiffness:50,start:{x:0,y:0,z:0,yaw:0,pitch:0,roll:0},end:{x:750,y:180,z:180,yaw:20,pitch:5,roll:35},minRadius:150,maxTwist:25,maxLength:1600};
export const add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),mul=(a,k)=>a.map(v=>v*k),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>Math.hypot(...a),unit=a=>mul(a,1/(norm(a)||1)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const pos=e=>[e.x,e.y,e.z],rad=Math.PI/180;
export function rotate(v,k,a){return add(add(mul(v,Math.cos(a)),mul(cross(k,v),Math.sin(a))),mul(k,dot(k,v)*(1-Math.cos(a))));}
export function axes(e){let y=e.yaw*rad,p=e.pitch*rad,t=[Math.cos(p)*Math.cos(y),Math.cos(p)*Math.sin(y),Math.sin(p)],a=rotate([-Math.sin(y),Math.cos(y),0],t,e.roll*rad);return {t,a,b:cross(t,a)};}
export function transport(a,t,u){let c=cross(t,u),sn=norm(c),cs=clamp(dot(t,u),-1,1);return sn<1e-10?(cs>0?a:rotate(a,unit(cross(t,a)),Math.PI)):rotate(a,mul(c,1/sn),Math.atan2(sn,cs));}
export function normalize(value){const s=structuredClone(defaults);if(!value||typeof value!=='object'||Array.isArray(value)||!['width','height','start','end'].every(k=>Object.hasOwn(value,k)))throw Error('Invalid design file');for(const k of Object.keys(defaults))if(Object.hasOwn(value,k))s[k]=structuredClone(value[k]);if(value.material!==undefined){if(!value.material||typeof value.material!=='object'||Array.isArray(value.material))throw Error('Invalid material measurements');s.material={...structuredClone(materialDefaults),...structuredClone(value.material)};}if(value.steel!==undefined){if(!value.steel||typeof value.steel!=='object'||Array.isArray(value.steel))throw Error('Invalid steel settings');s.steel={...structuredClone(steelDefaults),...structuredClone(value.steel)};}migrateEdgeLips(s);return s;}
export function prepareLoadedDesign(value){
 const settings=normalize(value);let notice=typeof settings.sectionMigration?.notice==='string'?settings.sectionMigration.notice:'';
 if(settings.steel.enabled){
  const probe=structuredClone(settings);probe.steel.enabled=false;probe.calibration=null;
  if(!validate(probe)&&(!supportsSteel(settings)||validateSteelPlacement(settings))){
   if(settings.calibration)settings.steel.inactiveCalibration=structuredClone(settings.calibration);
   settings.steel.enabled=false;settings.calibration=null;
   notice+=(notice?' ':'')+'Design restored. Previous steel settings are kept inactive: reinforcement is limited to T-ribs in 91-22ROS and 91-32ROS. Any assembly calibration is also inactive. Review the steel arrangement before enabling it.';
  }
 }
 const error=validate(settings);if(error)throw Error(error);return {settings,notice};
}
export function validate(s){
 if(s.material!==undefined){const e=validateMaterial(s.material,s);if(e)return e;}
 if(!['solid','hollow','ribbed'].includes(s.section||'solid'))return 'Choose a solid, hollow or ribbed section.';
 const sectionError=validateSection(s);if(sectionError)return sectionError;
 if(s.section==='hollow'&&(!Number.isFinite(s.wall)||s.wall<=0||2*s.wall>=Math.min(s.width,s.height)))return 'Wall thickness must be positive and less than half the smaller section dimension.';
 for(const [k,lo,hi]of[['startLead',0,1000],['endLead',0,1000],['rollRange',0,180],['maxStrain',0,20],['clearance',0,50]])if(s[k]!==undefined&&(!Number.isFinite(s[k])||s[k]<lo||s[k]>hi))return k+' is outside the supported range.';
 if(!['fixed','free','range'].includes(s.endRollMode||'fixed'))return 'Invalid end roll mode.';
 if(s.calibration){try{calibrationValues(s.calibration);}catch(e){return e.message;}if(s.calibration.signature!==signature(s))return 'Calibration belongs to a different section. Recalibrate or remove it.';}
 if(s.obstacles!==undefined&&!Array.isArray(s.obstacles)||(s.obstacles||[]).length>12)return 'Use at most 12 obstacles.';
 for(const o of s.obstacles||[]){if(!o||typeof o!=='object'||!['box','cylinder'].includes(o.type)||!['x','y','z','h',...(o.type==='box'?['w','d']:['radius'])].every(k=>Number.isFinite(o[k])&&Math.abs(o[k])<=10000)||o.h<=0||(o.type==='box'?(o.w<=0||o.d<=0):o.radius<=0))return 'Check obstacle sizes and positions.';}
 if(s.workspace!==undefined&&(!s.workspace||typeof s.workspace!=='object'||typeof s.workspace.enabled!=='boolean'))return 'Check workspace settings.';
 if(s.workspace&&!['x','y','z','w','d','h'].every(k=>Number.isFinite(s.workspace[k])&&Math.abs(s.workspace[k])<=10000&&(!['w','d','h'].includes(k)||s.workspace[k]>0)))return 'Check workspace dimensions.';
for(const [k,lo,hi]of[['width',1,150],['height',1,50],['stiffness',0,100],['minRadius',1,5000],['maxTwist',.1,180],['maxLength',10,5000]])if(!Number.isFinite(s[k])||s[k]<lo||s[k]>hi)return `${k} must be between ${lo} and ${hi}.`;const placement=validateSteelPlacement(s);if(placement)return placement;for(const end of ['start','end'])for(const k of ['x','y','z','yaw','pitch','roll'])if(!Number.isFinite(s[end]?.[k])||Math.abs(s[end][k])>(['x','y','z'].includes(k)?1000:k==='pitch'?90:180))return `Check ${end} ${k}.`;const D=norm(sub(pos(s.end),pos(s.start)));if(D<10)return 'Separate the endpoints by at least 10 mm.';if(D>1000.001)return 'Endpoint separation exceeds 1,000 mm. Move the endpoints closer.';if(s.maxLength<D)return 'Maximum path length is shorter than the endpoint separation.';if(norm(sub(add(pos(s.start),mul(axes(s.start).t,s.startLead||0)),sub(pos(s.end),mul(axes(s.end).t,s.endLead||0))))<10)return 'Straight leads leave less than 10 mm for the connecting curve.';return null;}
const choose=(n,k)=>{let r=1;for(let j=1;j<=k;j++)r=r*(n+1-j)/j;return r;};
const basisCache=new Map();function basis(N){if(basisCache.has(N))return basisCache.get(N);let out=[];for(let i=0;i<=N;i++){let t=i/N;out.push([7,6,5].map(n=>Array.from({length:n+1},(_,j)=>choose(n,j)*t**j*(1-t)**(n-j))));}basisCache.set(N,out);return out;}
function blend(cp,b){let p=[0,0,0];for(let j=0;j<cp.length;j++)for(let k=0;k<3;k++)p[k]+=cp[j][k]*b[j];return p;}
export const initialParams=()=>[1/7,1/7,0,0,0,0,0,0,0,0,0];
function controls(s,v){let a=axes(s.start),b=axes(s.end),p=add(pos(s.start),mul(a.t,s.startLead||0)),q=sub(pos(s.end),mul(b.t,s.endLead||0)),d=sub(q,p),L=norm(d);return[p,add(p,mul(a.t,L*v[0])),add(p,mul(a.t,2*L*v[0])),add(add(p,mul(d,3/7)),mul(v.slice(2,5),L)),add(add(p,mul(d,4/7)),mul(v.slice(5,8),L)),sub(q,mul(b.t,2*L*v[1])),sub(q,mul(b.t,L*v[1])),q];}
export function evaluate(s,v=initialParams(),N=100,full=true){
  v=[...v];while(v.length<11)v.push(0);const cp=controls(s,v),dc=cp.slice(0,-1).map((p,i)=>mul(sub(cp[i+1],p),7)),dd=dc.slice(0,-1).map((p,i)=>mul(sub(dc[i+1],p),6)),D=norm(sub(cp[7],cp[0])),base=basis(N),f0=axes(s.start),f1=axes({...s.end,roll:s.end.roll+(s.endRollMode==='free'?v[10]*180/Math.PI:s.endRollMode==='range'?clamp(v[10]*180/Math.PI,-s.rollRange,s.rollRange):0)}),samples=[];let L=0,kmax=0,kindex=0,minSpeed=Infinity;
  for(let i=0;i<=N;i++){let p=blend(cp,base[i][0]),v1=blend(dc,base[i][1]),v2=blend(dd,base[i][2]),speed=norm(v1),t=unit(v1),kv=mul(sub(v2,mul(t,dot(t,v2))),1/Math.max(speed*speed,1e-15)),k=norm(kv);minSpeed=Math.min(minSpeed,speed);if(i)L+=norm(sub(p,samples[i-1].p));if(k>kmax){kmax=k;kindex=i;}samples.push({p,t,kv,s:L,k,parameter:i/N,segment:'curve'});}
  let reversed=false;for(let i=1;i<=N;i++)if(dot(samples[i-1].t,samples[i].t)<.05)reversed=true;
  // Check between samples too: collinear cusps can have zero sampled curvature.
  const speed2=t=>{let b=Array.from({length:7},(_,j)=>choose(6,j)*t**j*(1-t)**(6-j)),vv=blend(dc,b);return dot(vv,vv);},speeds=base.map(b=>{let vv=blend(dc,b[1]);return dot(vv,vv);});
  for(let i=1;i<N;i++)if(speeds[i]<=speeds[i-1]&&speeds[i]<=speeds[i+1]){let lo=(i-1)/N,hi=(i+1)/N;for(let k=0;k<25;k++){const a=lo+(hi-lo)/3,b=hi-(hi-lo)/3;if(speed2(a)<speed2(b))hi=b;else lo=a;}minSpeed=Math.min(minSpeed,Math.sqrt(speed2((lo+hi)/2)));}
  if(reversed||minSpeed<Math.max(.01,D*1e-4)||!Number.isFinite(L))return{score:1e12,feasible:false,error:'Curve approaches a cusp or reverses abruptly. Change endpoint directions or allow more space.',params:v};
  let a=f0.a;samples[0].a=a;for(let i=1;i<=N;i++){a=transport(a,samples[i-1].t,samples[i].t);a=unit(sub(a,mul(samples[i].t,dot(a,samples[i].t))));samples[i].a=a;}
  const last=samples[N],turn=Math.atan2(dot(last.t,cross(last.a,f1.a)),clamp(dot(last.a,f1.a),-1,1)),geometry=sectionGeometry(s),props=rigidity(s),Iw=props.Bw,Ih=props.Bh,It=props.C,Iref=props.physical?2560*3000:2560;
  let elastic=0,physicalEnergy=0,twistMax=0,strainMax=0,strainIndex=0,steelStrainMax=s.steel?.enabled?0:null,foldMax=0,prevDensity=0;
  for(let i=0;i<=N;i++){const q=samples[i],u=q.s/L,ss=10*u**3-15*u**4+6*u**5,ssD=30*u*u*(1-u)*(1-u),sin=Math.sin(Math.PI*u),bump=sin*sin,blendRoll=v[8]*(1-u)+v[9]*u,roll=turn*ss+bump*blendRoll,omega=(turn*ssD+Math.PI*Math.sin(2*Math.PI*u)*blendRoll+bump*(v[9]-v[8]))/L;q.a=rotate(q.a,q.t,roll);q.b=cross(q.t,q.a);const ka=dot(q.kv,q.a),kb=dot(q.kv,q.b),strains=sectionStrains(geometry,ka,kb),strain=strains.pvc,density=(Iw*ka*ka+2*(props.Bwh||0)*ka*kb+Ih*kb*kb+It*omega*omega)/Iref;twistMax=Math.max(twistMax,Math.abs(omega)/rad*100);if(strain>strainMax){strainMax=strain;strainIndex=i;}if(i)elastic+=(density+prevDensity)/2*(q.s-samples[i-1].s);prevDensity=density;q.twist=omega/rad*100;q.strain=strain;q.steelStrain=strains.steel;foldMax=Math.max(foldMax,strains.fold);if(strains.steel!==null)steelStrainMax=Math.max(steelStrainMax,strains.steel);q.roll=roll;}
  const bendingEnergy=props.physical&&props.bendingOnly?elastic*Iref/2:null;physicalEnergy=props.physical&&!props.bendingOnly?elastic*Iref/2:null;elastic*=50;
  const curveLength=L,startLead=s.startLead||0,endLead=s.endLead||0;
  if(startLead){for(const q of samples)q.s+=startLead;const lead=[];for(let i=0,n=Math.max(1,Math.ceil(startLead/5));i<n;i++)lead.push({p:add(pos(s.start),mul(f0.t,startLead*i/n)),t:f0.t,a:f0.a,b:f0.b,kv:[0,0,0],s:startLead*i/n,parameter:null,segment:'inlet',k:0,twist:0,strain:0,steelStrain:s.steel?.enabled?0:null,roll:0});samples.unshift(...lead);kindex+=lead.length;strainIndex+=lead.length;}
  if(endLead){const end=samples.at(-1);for(let i=1,n=Math.max(1,Math.ceil(endLead/5));i<=n;i++)samples.push({p:add(end.p,mul(f1.t,endLead*i/n)),t:f1.t,a:f1.a,b:f1.b,kv:[0,0,0],s:startLead+curveLength+endLead*i/n,parameter:null,segment:'outlet',k:0,twist:0,strain:0,steelStrain:s.steel?.enabled?0:null,roll:turn});}
  L+=startLead+endLead;
  const radius=kmax>1e-10?1/kmax:null,violations=[Math.max(0,L/s.maxLength-1),Math.max(0,(radius?s.minRadius/radius:0)-1),Math.max(0,twistMax/s.maxTwist-1),Math.max(0,foldMax/.85-1),Math.max(0,s.maxStrain?strainMax/(s.maxStrain/100)-1:0)],violation=violations.reduce((a,b)=>a+b*b,0),q=10**((s.stiffness-50)/50),demand=q*elastic+L/1000,score=demand+1e5*violation,feasible=violations.every(x=>x<.0001);
  const result={score,demand,elastic,feasible,violation,violations,length:L,separation:norm(sub(pos(s.end),pos(s.start))),radius,twistMax,strainMax,strainIndex,kindex,params:v.slice(),stiffnessMultiplier:q,physicalEnergy,bendingEnergy,steelStrainMax,foldMax,actualEndRoll:s.end.roll+(s.endRollMode==='free'?v[10]/rad:s.endRollMode==='range'?clamp(v[10]/rad,-s.rollRange,s.rollRange):0)};if((s.obstacles||[]).length||s.workspace?.enabled){const hits=coarseContact({samples},s);result.score+=hits*1e4;result.contactCount=hits;}if(full){result.samples=samples;result.controls=cp;result.input=structuredClone(s);result.material=materialAssessment(s,strainMax);result.steel=s.steel?.enabled?{fit:s.steel.fit,youngMPa:s.steel.youngMPa,peakStrain:steelStrainMax,nominalBendingStressMPa:s.steel.youngMPa*steelStrainMax,note:'Linear-elastic bending estimate only; no steel yield, compression, torsion, friction or load-transfer check.'}:null;result.section=sectionRecord(s);result.rigidity={...props,units:props.physical?'N mm^2':'relative section geometry'};}return result;
}
function bounded(v){return v.map((x,i)=>clamp(x,i<2?.025:i<8?-.75:-Math.PI,i<2?.65:i<8?.75:Math.PI));}
export function solve(s,onProgress=()=>{}){s=normalize(s);const err=validate(s);if(err)return{error:err,feasible:false};let best=null;const candidates=[initialParams()],seeds=[initialParams(),[.28,.28,0,0,0,0,0,0,0,0],[.10,.10,0,0,.22,0,0,.22,1.2,1.2],[.22,.22,0,0,-.18,0,0,-.18,-1.2,-1.2]];
  for(const v of seeds)while(v.length<11)v.push(0);
  if(s.endRollMode!=='fixed'){for(const seed of seeds){const r=evaluate(s,seed,180,true);if(r.samples){seed[10]=clamp(-r.samples.at(-1).roll,s.endRollMode==='range'?-s.rollRange*rad:-Math.PI,s.endRollMode==='range'?s.rollRange*rad:Math.PI);}}}
  for(const v of seeds)candidates.push(v.slice());
  const better=(a,b)=>!b||a.score<b.score;
  for(let seed=0;seed<seeds.length;seed++){let v=seeds[seed],r=evaluate(s,v,64,false);for(let level=0;level<7;level++){const step=.12*2**(-level*.65);for(let pass=0;pass<2;pass++){let improved=false;for(let j=0;j<11;j++){if(j===10&&s.endRollMode==='fixed')continue;let winner=r,wv=v;for(const sign of [-1,1]){let candidate=v.slice();candidate[j]+=sign*step*(j<2?.6:j<8?1:5);candidate=bounded(candidate);let x=evaluate(s,candidate,64,false);if(better(x,winner)){winner=x;wv=candidate;}}if(wv!==v){if(r.feasible&&!winner.feasible)candidates.push(v.slice());improved=true;v=wv;r=winner;}}if(!improved)break;}candidates.push(v.slice());}onProgress({seed:seed+1,total:seeds.length});}
  // Re-score candidates on the same dense grid before comparison and report.
  const ranked=candidates.map(v=>evaluate(s,v,360,true)).sort((a,b)=>(b.feasible-a.feasible)||a.score-b.score);let alternatives=[];
  for(const x of ranked){if(x.error)continue;const duplicate=alternatives.some(r=>r.params.every((v,i)=>Math.abs(v-x.params[i])<1e-6));if(duplicate)continue;const checked=verify(s,x.params);alternatives.push(checked);if(checked.feasible){if(!best||!best.feasible||better(checked,best))best=checked;}else if(!best||(!best.feasible&&better(checked,best)))best=checked;}
  best=best||ranked[0];best.alternatives=alternatives.filter(x=>x.feasible).slice(0,3).map(x=>({params:x.params,length:x.length,radius:x.radius,twistMax:x.twistMax,strainMax:x.strainMax}));
  const baseDense=evaluate(s,initialParams(),360,true);if(best.error)return{...best,refined:true};
  best.baseline={length:baseDense.length,elastic:baseDense.elastic,demand:baseDense.demand,feasible:baseDense.feasible};best.refined=true;
  best.warnings=[];if(best.radius!==null&&best.radius<s.minRadius*.9999)best.warnings.push('Minimum bend radius');if(best.twistMax>s.maxTwist*1.0001)best.warnings.push('Maximum twist');if(best.length>s.maxLength*1.0001)best.warnings.push('Maximum path length');if(best.foldMax>.85)best.warnings.push('Section sweep folds');if(s.maxStrain&&best.strainMax>s.maxStrain/100)best.warnings.push('Peak strain target');if(best.clearance?.status!=='clear')best.warnings.push('Clearance '+(best.clearance?.status||'unchecked'));if(!best.convergence?.stable)best.warnings.push('Numerical refinement did not stabilise');return best;
}
export function verify(s,v){let previous=null,result=null,stable=false;for(const n of [180,360,720,1440]){result=evaluate(s,v,n,true);if(result.error)return result;if(previous){const change=(a,b)=>Math.abs(a-b)/Math.max(1e-9,Math.abs(b));stable=change(result.length,previous.length)<.0005&&change(result.twistMax,previous.twistMax)<.01&&change(result.strainMax,previous.strainMax)<.01&&change(result.foldMax,previous.foldMax)<.01&&(!s.steel?.enabled||change(result.steelStrainMax,previous.steelStrainMax)<.01)&&((!result.radius&&!previous.radius)||(result.radius&&previous.radius&&change(result.radius,previous.radius)<.01));}if(stable&&n>=720)break;previous=result;}result.convergence={stable,samples:result.samples.length,lengthTolerancePercent:.05,peakTolerancePercent:1};result.clearance=checkClearance(result,s);result.feasible=result.feasible&&stable&&result.clearance.status==='clear';result.refined=true;return result;}
export function stationData(r,spacing=10){if(!Number.isFinite(spacing)||spacing<.1||spacing>1000)throw Error('Invalid station spacing');if(!r.samples)throw Error('No current pathway');const rows=[];let j=0;for(let s=0;s<r.length;s+=spacing){while(j<r.samples.length-2&&r.samples[j+1].s<s)j++;rows.push(interpolate(r.samples[j],r.samples[j+1],s));}rows.push(interpolate(r.samples.at(-2),r.samples.at(-1),r.length));return rows;}
function interpolate(a,b,s){const f=clamp((s-a.s)/(b.s-a.s||1),0,1),mix=(x,y)=>add(mul(x,1-f),mul(y,f)),t=unit(mix(a.t,b.t)),uu=mix(a.a,b.a),u=unit(sub(uu,mul(t,dot(uu,t)))),v=cross(t,u);return{s,p:mix(a.p,b.p),t,a:u,b:v,curvature:a.k*(1-f)+b.k*f,twist:a.twist*(1-f)+b.twist*f,strain:a.strain*(1-f)+b.strain*f,steelStrain:a.steelStrain==null||b.steelStrain==null?null:a.steelStrain*(1-f)+b.steelStrain*f};}
