import {add,sub,mul,dot,norm,pos} from './solver.mjs';
import {sectionGeometry,envelopeLoop,sectionPoint} from './section.mjs';
export class PathView{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.az=-.85;this.el=.52;this.zoom=1;this.model=null;this.pan=[0,0];this.resize=new ResizeObserver(()=>this.draw());this.resize.observe(canvas);let drag=null;canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag)return;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag={x:e.clientX,y:e.clientY};if(e.shiftKey||e.buttons===2){this.pan[0]+=dx;this.pan[1]+=dy;}else{this.az-=dx*.008;this.el=Math.max(-1.5,Math.min(1.5,this.el+dy*.008));document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'));}this.draw();});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>drag=null);canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom=Math.max(.25,Math.min(5,this.zoom*Math.exp(-e.deltaY*.001)));this.draw();},{passive:false});}
 set(model,state){this.model=model;this.state=state;this.draw();}
 fit(){this.zoom=1;this.pan=[0,0];this.draw();}
 view(v){const settings={'3d':[-.85,.52],top:[-Math.PI/2,Math.PI/2],side:[-Math.PI/2,0],end:[0,0]};[this.az,this.el]=settings[v];this.fit();}
 draw(){const c=this.canvas,ctx=this.ctx,W=c.clientWidth,H=c.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(c.width!==Math.round(W*dpr)||c.height!==Math.round(H*dpr)){c.width=Math.round(W*dpr);c.height=Math.round(H*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);if(!this.model?.samples)return;
  const r=this.model,s=this.state,geometry=sectionGeometry(s),ss=r.samples,center=mul(add(pos(s.start),pos(s.end)),.5),all=ss.map(q=>q.p),radius=Math.max(...all.map(p=>norm(sub(p,center))))+Math.max(...geometry.vertices.map(p=>Math.hypot(...p)))+(s.clearance||0),scale=Math.min((W-110)/(2*radius||1),(H-130)/(2*radius||1))*this.zoom;
  const ca=Math.cos(this.az),sa=Math.sin(this.az),ce=Math.cos(this.el),se=Math.sin(this.el),right=[-sa,ca,0],up=[-se*ca,-se*sa,ce],depth=[ce*ca,ce*sa,se];
  const proj=p=>{let q=sub(p,center);return[W/2+dot(q,right)*scale+this.pan[0],H/2-dot(q,up)*scale+this.pan[1],dot(q,depth)];};
  const path=(points,stroke,width=1,close=false,fill=null)=>{ctx.beginPath();points.forEach((p,i)=>{let q=proj(p);i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1]);});if(close)ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}};
  // The grid is a fixed world XY plane, in 100 mm increments.
  let minX=Math.floor((center[0]-Math.max(radius,500))/100)*100,maxX=Math.ceil((center[0]+Math.max(radius,500))/100)*100,minY=Math.floor((center[1]-Math.max(radius,500))/100)*100,maxY=Math.ceil((center[1]+Math.max(radius,500))/100)*100,z=Math.min(0,...ss.map(q=>Math.min(...geometry.vertices.map(p=>sectionPoint(q,p)[2]))))-10;
  for(let x=minX;x<=maxX;x+=100)path([[x,minY,z],[x,maxY,z]],'#263645',.6);for(let y=minY;y<=maxY;y+=100)path([[minX,y,z],[maxX,y,z]],'#263645',.6);
  const corners=q=>geometry.loops[0].map(p=>sectionPoint(q,p)),edgeCount=geometry.loops[0].length;
  let rings=ss.filter((q,i)=>i%6===0).map(q=>({q,c:corners(q)}));if(rings.at(-1).q!==ss.at(-1))rings.push({q:ss.at(-1),c:corners(ss.at(-1))});let faces=[];for(let i=0;i<rings.length-1;i++)for(let k=0;k<edgeCount;k++){let points=[rings[i].c[k],rings[i].c[(k+1)%edgeCount],rings[i+1].c[(k+1)%edgeCount],rings[i+1].c[k]],dep=points.reduce((a,p)=>a+proj(p)[2],0)/4;faces.push({points,dep,k,q:rings[i].q});}faces.sort((a,b)=>a.dep-b.dep);const value=q=>this.colorMode==='twist'?Math.abs(q.twist):this.colorMode==='strain'?q.strain:q.k,maxValue=Math.max(...ss.map(value),1e-9);for(const f of faces){const ratio=Math.min(1,value(f.q)/maxValue),color='hsla('+(172-ratio*155)+',65%,'+(42+(f.k%4)*4)+'%,.9)';path(f.points,null,0,true,color);}
  for(let k=0;k<edgeCount;k++)path(rings.map(r=>r.c[k]),'#b0c9d7',.8);for(let i=0;i<rings.length;i+=6)path(rings[i].c,'#476477',.7,true);ctx.setLineDash([3,6]);path(ss.map(q=>q.p),'#e0eff988',1);ctx.setLineDash([]);
  for(const [q,label,color]of[[ss[0],'START','#5de4da'],[ss.at(-1),'END','#ffc879']]){for(const loop of geometry.loops)path(loop.map(p=>sectionPoint(q,p)),color,2.5,true);const p=proj(q.p),tip=proj(add(q.p,mul(q.t,70))),dx=tip[0]-p[0],dy=tip[1]-p[1],dn=Math.hypot(dx,dy)||1;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(tip[0],tip[1]);ctx.lineTo(tip[0]-dx/dn*8+dy/dn*4,tip[1]-dy/dn*8-dx/dn*4);ctx.moveTo(tip[0],tip[1]);ctx.lineTo(tip[0]-dx/dn*8-dy/dn*4,tip[1]-dy/dn*8+dx/dn*4);ctx.stroke();ctx.font='600 11px "DM Sans", sans-serif';ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(label,p[0],p[1]+(label==='START'?-26:36));}
  if(geometry.steelParts.length){
   for(const part of geometry.steelParts){for(const p of part.loop)path(rings.map(r=>sectionPoint(r.q,p)),'#ffd28b',1.2);for(const q of [ss[0],ss.at(-1)])path(part.loop.map(p=>sectionPoint(q,p)),'#fff0ce',1.5,true,'#dba853');}
   ctx.font='12px system-ui,sans-serif';ctx.textAlign='right';ctx.fillStyle='#ffd28b';ctx.fillText('Gold: steel shown through PVC',W-18,H-20);
  }
  if(s.clearance>0){ctx.setLineDash([3,4]);for(let i=0;i<rings.length;i+=10){const q=rings[i].q,cc=envelopeLoop(geometry,s.clearance).map(p=>sectionPoint(q,p));path(cc,'#72d4dc88',1,true);}ctx.setLineDash([]);}
  if(Number.isFinite(this.station)){const q=ss.reduce((a,b)=>Math.abs(b.s-this.station)<Math.abs(a.s-this.station)?b:a);for(const loop of geometry.loops)path(loop.map(p=>sectionPoint(q,p)),'#ffffff',2,true);const pp=proj(q.p);ctx.beginPath();ctx.arc(pp[0],pp[1],4,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();}
  for(const o of [...(s.obstacles||[]),...(s.workspace?.enabled?[{...s.workspace,type:'box',workspace:true}]:[])]){const col=o.workspace?'#a8c3d577':'#f2968a';if(o.type==='box'){let p=Array.from({length:8},(_,i)=>[o.x+(i&1?1:-1)*o.w/2,o.y+(i&2?1:-1)*o.d/2,o.z+(i&4?1:-1)*o.h/2]);for(let i=0;i<8;i++)for(const k of [1,2,4])if(!(i&k))path([p[i],p[i|k]],col,1);}else{const circle=z=>Array.from({length:40},(_,i)=>[o.x+o.radius*Math.cos(i/40*Math.PI*2),o.y+o.radius*Math.sin(i/40*Math.PI*2),z]);path(circle(o.z-o.h/2),col,1,true);path(circle(o.z+o.h/2),col,1,true);for(let i=0;i<4;i++){let x=o.x+o.radius*Math.cos(i*Math.PI/2),y=o.y+o.radius*Math.sin(i*Math.PI/2);path([[x,y,o.z-o.h/2],[x,y,o.z+o.h/2]],col,1);}}}
  // World-axis indicator stays readable while the camera orbits.
  const ox=40,oy=H-60;ctx.font='12px "DM Sans",sans-serif';ctx.textAlign='center';for(const [a,l,col]of[[[1,0,0],'X','#9eb2c3'],[[0,1,0],'Y','#9eb2c3'],[[0,0,1],'Z','#9eb2c3']]){const dx=dot(a,right)*24,dy=-dot(a,up)*24;if(Math.hypot(dx,dy)<2)continue;ctx.beginPath();ctx.moveTo(ox,oy);ctx.lineTo(ox+dx,oy+dy);ctx.strokeStyle=col;ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=col;ctx.fillText(l,ox+dx*1.4,oy+dy*1.4+4);}
 }
}
